### ISSUE TITLE
Collapsing algorithm

### ISSUE THREAD

**Issue by Sytten** [cafaro/UDDSketch#2]
I have another small question regarding the collapsing algorithm itself. 

Reading the paper and the current repository, they both seem to match the algorithm 2. My understanding is that this algorithm is made for sparse sketches since (i+1) doesn't always exist so it is more efficient to divide all indices by two.

Reading the PUUDsketch repository, it seems to match the algorithm explained in the text before algorithm 2 (`indices (i, i+1) where i is odd...`). This seems to be for dense scketches. 

Ultimately I understand they both achieve the same result, but it was a source of confusion for me when reading the paper so I just want to confirm.

**Comment by cafaro** [comment]
I've reviewed the parallel code (MapSketch.cc file) with my colleagues, and the strategy used is always to divide the index by 2, when you collapse the sketch in the parallel computation section: from this point of view there are no differences with respect to the sequential code available in the UDDSketch repository and your observation is not entirely clear to me. 

Regarding the optimization of the procedure for dense structures (if we consider the current implementation as an optimization for the sparse case), we do not think it is possible to do any better, given the logic of the uniform collapsing procedure.

Hope this helps.

**Comment by Sytten** [comment]
Agreed, for maps the algorithm is the same in UDDSketch and PUDDSKETCH and is the algorithm 2 in the paper (for sparse structures).
I was referring to the optimization for array/dense structures (ArraySketch.cc) that was source of confusing for me when reading the paper because it didn't mention sparse vs dense differences.
I just wanted to make the issue so if other people reading the paper are confused at least they know which algorithm/optimization can be used for each type of data structure.

**Comment by cafaro** [comment]
Ok, now everything is clear. The code you see in ArraySketch.cc is specific to the parallel implementation of UDDSketch. Indeed, that code refers technically to a user's defined parallel reduction in which we merge the sketches belonging to the processes. For the reduction, the sketches are represented by arrays of buckets, and the merged sketch is obtained by iterating through the indexes of the two input arrays and inserting as needed the buckets in the new, merged sketch. Only at the end of this process, if the number of buckets exceeds the bucket number then a collapse procedure is executed. 

For DDSketch there is a (minor) optimization instead:  when we arrive at the next-to-last bucket the remaining count is collapsed into the last bucket. 

Therefore, the difference you see in the parallel implementation is related to the data structure used in two different moments of the algorithm: an hash table (a  C++ map) is used in each parallel process to store the process' input items; and an array is used instead for the custom parallel reduce operator.

The preprint I told you is now available on arXiv. If interested, you can download it from here: https://arxiv.org/abs/2101.06758

With kind regards,
Massimo
